### ISSUE TITLE
Invalid Cookie Header

### ISSUE THREAD

**Issue by hopeseekr** [Stadly/TimelineExtractor#2]
ValueError: Invalid header value b'cookie=SID=VAjEMGA3XUp

I don't think it works anymore.

**Comment by Stadly** [comment]
What input did you use to run it?

**Comment by Stadly** [comment]
Try turning on debug output so we can see what happens: `python extract.py -l debug ...`

**Comment by Stadly** [comment]
I haven't used the script in quite a while. Tried it now and couldn't get it to work. It definitely seems like Google changed something. I'll see if I can find a fix for it, but it might take some time before I can look into it.

**Comment by Egregius** [comment]
Hi Stadly,
Did you had any chance of looking into this?

**Comment by Stadly** [comment]
I have unfortunately not had a chance to look at it yet 😞
